### PR TITLE
[CLB-27] Investigate free chart libraries

### PR DESCRIPTION
**Pull request by Mbotunjac**
Added Victory free chart library, seemed like a best fit, especially because of a good documentation that I think is a good thing for us. 

Also made a chart just to test it and see how everything works (I apologize about chart theme, had a low inspiration) 

Important!
Need feedback on README file I implemented in the Charts folder. 
Wanted to give us all an easy access to Victory doc. and info on how to use it in general, but not 100% sure if this is a proper way.
Here are also links just in case 
[https://github.com/formidablelabs/victory](url)
[https://formidable.com/open-source/victory/gallery](url)

### CODE REVIEW

**Comment by kimnovak** [comment]
Vercel was facing some issues yesterday so it didn't trigger the deployment
Can you please make a change somewhere in the code, perhaps that ReadMe file you added, and commit & push to try to trigger it today?

**Comment by Mbotunjac** [comment]
> Vercel was facing some issues yesterday so it didn't trigger the deployment Can you please make a change somewhere in the code, perhaps that ReadMe file you added, and commit & push to try to trigger it today?

Sure, no problem

**Comment by Mbotunjac** [comment]
I see there is also a conflict now, will fix it and try again

**Comment by Mbotunjac** [comment]
Looks like Vercel is ok now and conflicts are fixed

**Pull request merged**
